name: shared_preferences_debugger
description: This package is designed to simplify the debugging of the shared_preferences plugin package.
version: 0.1.0
repository: https://github.com/HTsuruo/shared_preferences_debugger

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  clipboard: ^0.1.3
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.22.0
